

# These are a list of server IDs that are forcefully disabled on this server.
# Just add one of the corresponding mod IDS to this list.

# Mod Ids: (Last Updated: 02/04/2021)
# one_seven_visuals - 1.7 Visuals
# fps - FPS
# cps - CPS
# skyblockAddons - Skyblock Addons
# toggleSneak - Toggle Sneak/Sprint
# hypixel_mod - Hypixel Mods
# armorstatus - Armor Status
# keystrokes - Key Strokes
# coords - Coordinates
# crosshair - Crosshair
# potioneffects - Potion Effects
# directionhud - Direction HUD
# waypoints - Waypoints
# scoreboard - Scoreboard
# potion_counter - Potion Counter
# ping - Ping
# motionBlur - Motion Blur
# chat - Chat
# scrollable_tooltips - Scrollable Tooltips
# uhc_overlay - UHC Overlay
# particleMultiplierMod - Particle Multiplier
# cooldowns - Cooldowns
# worldedit_cui - WorldEdit CUI
# clock - Clock
# stopwatch - Stopwatch
# memory - Memory Usage
# combo - Combo Counter
# range - Reach Display
# time_changer - Time Changer
# serverAddressMod - Server Address
# saturation - Saturation
# itemPhysic - Item Physics
# itemTrackerChild - Item Tracker
# shinyPots - Shiny Pots
# block_outline - Block Outline
# screenshot - Screenshot Uploader
# fov_mod - FOV Mod
# textHotKey - Auto Text Hot Key
# netgraph - Net Graph
# mumble-link - Mumble Link
# bossbar - Boss Bar
# freelook - Freelook
force-disabled-mods:
  - "skyblockAddons" # Lets disable SkyBlockAddons mod for example.

# The server rules that the server forces for the Lunar Client player.
# A lot of these are cosmetics, and don't affect gameplay.
server-rules:
  SERVER_HANDLES_WAYPOINTS: false
  COMPETITIVE_GAME: false
  SHADERS_DISABLED: false
  LEGACY_ENCHANTING: false
  LEGACY_COMBAT: false


# All of the fields with there types MUST be here for each waypoint,
# otherwise the plugin will likely not work when loading.
# Here is an example of one:
waypoints:
  - Spawn: # The same name as the waypoint.
      x: 0 # Must be a number, -inf->inf. No decimals. No quotes.
      y: 100 # Must be a number, 0->255. No decimals. No quotes.
      z: 0 # Must be a number, -inf->inf. No decimals. No quotes.
      name: "Spawn" # MUST be a word, and MUST be in quotes.
      world: "world" # MUST be a word, and MUST be in quotes. MUST be a valid world name.
      color: 0xFF0000 # MUST be a hexadecimal representation of a number.
      forced: false # MUST be either a true or false value. No quotes.
      visible: true # MUST be either a true or false value. No quotes.
